#!/usr/bin/env python3
"""
Validate the merged AsyncAPI 3.0 YAML generated by 'specmatic kafka-asyncapi-merged'.

Usage:
  python validate-asyncapi.py \
    --merged-spec asyncapi-specs/all-kafka-events.yaml \
    [--inferred-schemas-dir inferred-schemas]
"""

import argparse, json, sys, yaml
from pathlib import Path

REQUIRED_TOP_LEVEL_KEYS = {"asyncapi", "info", "servers", "channels", "operations", "components"}


def _read_metadata(inferred_dir: Path, topic: str) -> dict:
    meta_file = inferred_dir / topic / "metadata.json"
    if meta_file.exists():
        try:
            return json.loads(meta_file.read_text())
        except Exception:
            pass
    return {}


def _schema_stems(inferred_dir: Path, topic: str) -> list[str]:
    """Schema file stems for a topic, excluding metadata.json, sorted."""
    return [
        f.stem for f in sorted((inferred_dir / topic).glob("*.json"))
        if f.name != "metadata.json"
    ]


def validate_merged_spec(spec_file: Path, inferred_dir: Path, expected_topics: int = 6) -> list[str]:
    errors = []

    if not spec_file.exists():
        return [f"File not found: {spec_file}"]

    try:
        spec = yaml.safe_load(spec_file.read_text())
    except yaml.YAMLError as e:
        return [f"Invalid YAML: {e}"]

    if spec.get("asyncapi") != "3.0.0":
        errors.append(f"Expected asyncapi: 3.0.0, got: {spec.get('asyncapi')}")

    for key in REQUIRED_TOP_LEVEL_KEYS:
        if key not in spec:
            errors.append(f"Missing top-level key: '{key}'")

    channels   = spec.get("channels")   or {}
    operations = spec.get("operations") or {}
    messages   = (spec.get("components") or {}).get("messages") or {}

    if len(channels) != expected_topics:
        errors.append(
            f"Expected {expected_topics} channels, got {len(channels)}: {list(channels.keys())}"
        )

    if len(operations) != expected_topics:
        errors.append(
            f"Expected {expected_topics} operations, got {len(operations)}: {list(operations.keys())}"
        )

    msg_keys = list(messages.keys())
    duplicates = [k for k in set(msg_keys) if msg_keys.count(k) > 1]
    if duplicates:
        errors.append(f"Duplicate message keys in merged spec: {duplicates}")

    # Every schema file in inferred-schemas/ must appear in components.messages
    if inferred_dir.is_dir():
        for topic_dir in sorted(inferred_dir.iterdir()):
            if not topic_dir.is_dir():
                continue
            for stem in _schema_stems(inferred_dir, topic_dir.name):
                if stem not in messages:
                    errors.append(
                        f"[{topic_dir.name}] '{stem}.json' has no matching entry "
                        f"in components.messages"
                    )

    # inferred-events: EXPLICIT_SINGLE with discriminator 'action'; const present on each message
    if (inferred_dir / "inferred-events").is_dir():
        meta = _read_metadata(inferred_dir, "inferred-events")
        if meta.get("discriminatorResultType") == "EXPLICIT_SINGLE":
            if meta.get("discriminatorField") != "action":
                errors.append(
                    f"[inferred-events] Expected discriminatorField 'action', "
                    f"got '{meta.get('discriminatorField')}'"
                )
            expected_consts = {"ITEM_ADDED", "ITEM_REMOVED", "INVENTORY_ADJUSTED"}
            found_consts = set()
            for key in expected_consts:
                msg_def = messages.get(key) or {}
                props = (msg_def.get("payload") or {}).get("properties") or {}
                for prop_schema in props.values():
                    if isinstance(prop_schema, dict) and "const" in prop_schema:
                        found_consts.add(prop_schema["const"])
            missing = expected_consts - found_consts
            if missing:
                errors.append(
                    f"[inferred-events] Missing const values in merged spec: {sorted(missing)}"
                )

    # order/payment/user-events: EXPLICIT_SINGLE with discriminator 'eventType'; const present on each message
    EXPLICIT_EVENTTYPE_TOPICS = {
        "order-events":   {"ORDER_CREATED", "ORDER_SHIPPED", "ORDER_CANCELLED"},
        "payment-events": {"PAYMENT_INITIATED", "PAYMENT_COMPLETED", "PAYMENT_FAILED"},
        "user-events":    {"USER_REGISTERED", "USER_UPDATED", "USER_DELETED"},
    }
    for topic, expected_messages in EXPLICIT_EVENTTYPE_TOPICS.items():
        if not (inferred_dir / topic).is_dir():
            continue
        topic_meta = _read_metadata(inferred_dir, topic)
        if topic_meta.get("discriminatorResultType") == "EXPLICIT_SINGLE":
            if topic_meta.get("discriminatorField") != "eventType":
                errors.append(
                    f"[{topic}] Expected discriminatorField 'eventType', "
                    f"got '{topic_meta.get('discriminatorField')}'"
                )
            for msg_name in expected_messages:
                msg_def = messages.get(msg_name) or {}
                props = (msg_def.get("payload") or {}).get("properties") or {}
                event_type_schema = props.get("eventType") or {}
                if "const" not in event_type_schema:
                    errors.append(
                        f"[{topic}] {msg_name}.eventType should be const, "
                        f"got: {event_type_schema}"
                    )

    # untyped-events: single structure → exactly 1 schema file
    if (inferred_dir / "untyped-events").is_dir():
        untyped_stems = _schema_stems(inferred_dir, "untyped-events")
        if len(untyped_stems) != 1:
            errors.append(
                f"[untyped-events] Expected 1 schema file, "
                f"found {len(untyped_stems)}: {untyped_stems}"
            )

    # shape-events: IMPLICIT_SHAPE → >= 2 cluster signatures and >= 2 schema files
    if (inferred_dir / "shape-events").is_dir():
        shape_meta = _read_metadata(inferred_dir, "shape-events")
        if shape_meta.get("discriminatorResultType") == "IMPLICIT_SHAPE":
            sigs = shape_meta.get("clusterSignatures", [])
            if len(sigs) < 2:
                errors.append(
                    f"[shape-events] Expected >= 2 clusterSignatures in metadata.json, "
                    f"got {len(sigs)}"
                )
            shape_stems = _schema_stems(inferred_dir, "shape-events")
            if len(shape_stems) < 2:
                errors.append(
                    f"[shape-events] Expected >= 2 schema files, "
                    f"found {len(shape_stems)}: {shape_stems}"
                )

    return errors


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--merged-spec",          required=True,  type=Path)
    parser.add_argument("--inferred-schemas-dir", required=False, type=Path,
                        default=Path("inferred-schemas"))
    parser.add_argument("--expected-topics",      required=False, type=int, default=6,
                        help="Expected number of channels/operations in the merged spec (default: 6)")
    args = parser.parse_args()

    errors = validate_merged_spec(args.merged_spec, args.inferred_schemas_dir, args.expected_topics)
    if errors:
        print(f"  FAIL  {args.merged_spec.name}:")
        for e in errors:
            print(f"          - {e}")
        print("\nAsyncAPI validation failed.")
        sys.exit(1)
    else:
        print(f"  PASS  merged spec: {args.merged_spec.name}")
        print("\nAsyncAPI spec validated successfully.")


if __name__ == "__main__":
    main()
