#!/usr/bin/env python3
"""
Validate AsyncAPI 3.0 YAML files generated by 'specmatic kafka-asyncapi'.

Usage:
  python validate-asyncapi.py \
    --asyncapi-dir asyncapi-specs \
    --inferred-schemas-dir inferred-schemas
"""

import argparse, sys, yaml
from pathlib import Path

REQUIRED_TOP_LEVEL_KEYS = {"asyncapi", "info", "servers", "channels", "operations", "components"}

def validate_spec(spec_file: Path, inferred_dir: Path, topic: str) -> list[str]:
    """Returns a list of error strings (empty = PASS)."""
    errors = []

    try:
        with open(spec_file) as f:
            spec = yaml.safe_load(f)
    except yaml.YAMLError as e:
        return [f"Invalid YAML: {e}"]

    if spec.get("asyncapi") != "3.0.0":
        errors.append(f"Expected asyncapi: 3.0.0, got: {spec.get('asyncapi')}")

    for key in REQUIRED_TOP_LEVEL_KEYS:
        if key not in spec:
            errors.append(f"Missing top-level key: '{key}'")

    messages = (spec.get("components") or {}).get("messages") or {}

    # Every *.json file from Stage 1 should have a corresponding message
    schema_files = list((inferred_dir / topic).glob("*.json"))
    for schema_file in schema_files:
        event_type = schema_file.stem
        if event_type not in messages:
            errors.append(
                f"Event type '{event_type}' (from {schema_file.name}) "
                f"is missing from components.messages"
            )

    # Each message's payload should have const on the discriminator field
    # (Heuristic: look for any property with a 'const' key — the exact
    #  discriminator field name is not known here without re-reading the config)
    for msg_name, msg_def in messages.items():
        payload = (msg_def or {}).get("payload") or {}
        properties = payload.get("properties") or {}
        has_const = any("const" in (v or {}) for v in properties.values() if isinstance(v, dict))
        if not has_const:
            errors.append(
                f"Message '{msg_name}': no property with 'const' found in payload. "
                f"Discriminator field may not have been converted correctly."
            )

    return errors


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--asyncapi-dir",         required=True, type=Path)
    parser.add_argument("--inferred-schemas-dir", required=True, type=Path)
    args = parser.parse_args()

    topics = [d.name for d in args.inferred_schemas_dir.iterdir() if d.is_dir()]
    overall_pass = True

    for topic in sorted(topics):
        spec_file = args.asyncapi_dir / f"{topic}.yaml"
        if not spec_file.exists():
            print(f"  FAIL  {topic}: {spec_file} not found")
            overall_pass = False
            continue

        errors = validate_spec(spec_file, args.inferred_schemas_dir, topic)
        if errors:
            print(f"  FAIL  {topic}:")
            for e in errors:
                print(f"          - {e}")
            overall_pass = False
        else:
            print(f"  PASS  {topic}: {spec_file.name}")

    if not overall_pass:
        print("\nAsyncAPI validation failed.")
        sys.exit(1)
    else:
        print("\nAll AsyncAPI specs validated successfully.")


if __name__ == "__main__":
    main()
